var1=input("Introduce la primera palabra")
var2=input("Introduce la segunda palabra")
var3=input("Introduce la tercera palabra")
var4=input("Introduce la vuarta palabra")
var5=input("Introduce la quinta palabra")
print(f"{var1}, {var2}, {var3}, {var4}, {var5}")